### PR TITLE
Fixed links to past editions.

### PR DESCRIPTION
**Pull request by ebezzam**
This PR addresses issue #14

### CODE REVIEW

**Review by pokitoz — COMMENTED** [review]
I am not sure. It looks like the link variable is appended to the link:
http://lauzhack.com/2017.lauzhack.com
If you do that it will become:
http://lauzhack.com/http://2017.lauzhack.com

LauzHack.github.io-past_edition_links/{edition.link}

**Comment by ebezzam** [comment]
Also thought the same, but when I built/served locally it worked 🙈(redirected to `http://2016 .lauzhack.com/` and `http://2017.lauzhack.com/ ` as expected). I've seen this before that when you don't put `http://` the site will think it's a relative link. @SolalPirelli can confirm 😄

**Comment by pokitoz** [comment]
You are probably right, I have no idea how that works!

**Comment by SolalPirelli** [comment]
Thanks!

**Pull request merged**
